// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDfW7vPa14KHOjCguzm8bjGUToRKj6qM',
    appId: '1:1081807849735:web:df3e1291fd42e775a71da2',
    messagingSenderId: '1081807849735',
    projectId: 'inclass17-de208',
    authDomain: 'inclass17-de208.firebaseapp.com',
    storageBucket: 'inclass17-de208.firebasestorage.app',
    measurementId: 'G-GCPJP66T47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1p0n0QI47U6waYhmt-M1byiARWGxqcnw',
    appId: '1:1081807849735:android:74142852a33bf583a71da2',
    messagingSenderId: '1081807849735',
    projectId: 'inclass17-de208',
    storageBucket: 'inclass17-de208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQEUwu5q23zZtLlVFR4XLm34aCXeBhSnA',
    appId: '1:1081807849735:ios:34ac288c899923f8a71da2',
    messagingSenderId: '1081807849735',
    projectId: 'inclass17-de208',
    storageBucket: 'inclass17-de208.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQEUwu5q23zZtLlVFR4XLm34aCXeBhSnA',
    appId: '1:1081807849735:ios:34ac288c899923f8a71da2',
    messagingSenderId: '1081807849735',
    projectId: 'inclass17-de208',
    storageBucket: 'inclass17-de208.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhDfW7vPa14KHOjCguzm8bjGUToRKj6qM',
    appId: '1:1081807849735:web:ba223459be04c641a71da2',
    messagingSenderId: '1081807849735',
    projectId: 'inclass17-de208',
    authDomain: 'inclass17-de208.firebaseapp.com',
    storageBucket: 'inclass17-de208.firebasestorage.app',
    measurementId: 'G-7WFJPRZ6SS',
  );
}
